### ISSUE TITLE
Update documentation to add sqlite schema

### ISSUE THREAD

**Issue by mcarbonneaux** [Castaglia/proftpd-mod_conf_sql#17]
in documentation at https://htmlpreview.github.io/?https://github.com/Castaglia/proftpd-mod_conf_sql/blob/master/mod_conf_sql.html you don't have sqlite schema example, but seem to exist her: https://github.com/Castaglia/proftpd-mod_conf_sql/blob/master/sqlite-conf.sql

```
CREATE TABLE IF NOT EXISTS ftpctx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent_id INTEGER UNSIGNED,
  name TEXT,
  type TEXT,
  value TEXT
);

CREATE TABLE IF NOT EXISTS ftpconf (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  value BLOB
);

CREATE TABLE IF NOT EXISTS ftpmap (
  conf_id INTEGER UNSIGNED NOT NULL,
  ctx_id INTEGER UNSIGNED NOT NULL
);
```

**Comment by mcarbonneaux** [comment]
i've added pr https://github.com/Castaglia/proftpd-mod_conf_sql/pull/18

**Comment by Castaglia** [comment]
PR merged to master.  Thanks!
