### ISSUE TITLE
when proftpd recieve restart (SIGHUP) they not reload configuration...

### ISSUE THREAD

**Issue by mcarbonneaux** [Castaglia/proftpd-mod_conf_sql#5]
when read the configuration in sqlconf_conf they not reinitialise sqlconf_confi read counter at the end of the configuration read.
then when proftpd restart, sqlconf_confi are at the last position and canot send the readed sql configuration (they are readed in new array, the old are not destroy!).

i've modifyed the source to reinitialise sqlconf_confi at array creation (after make_array call)
and use file_handle pool in place of sql_conf pool.
and set to NULL sqlconf_conf at the end of configuration.

this modification ar in my pull request https://github.com/Castaglia/proftpd-mod_conf_sql/pull/4

**Comment by Castaglia** [comment]
This should now be fixed in master.  Thanks!
